jdbc:
  dbname: film_rating
  host: localhost
  dbPort: 3306
  password: password
  username: root

redis:
  host: localhost
  port: 6379
  timeout: 60000

spring:
  application:
    name: api-film-rating

  datasource:
    url: jdbc:mysql://${jdbc.host}:${jdbc.dbPort}/${jdbc.dbname}?autoReconnect=true&useSSL=true
    username: ${jdbc.username}
    password: ${jdbc.password}
    validationQuery: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update # Automatically updates the schema; change to validate, create, or none as needed
      show-sql: true # Enables SQL logging in the console
      open-in-view: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    enabled: true
    change-log: "classpath:db.changelog-master.yaml"
    database-change-log-table: databasechangelog
    database-change-log-lock-table: databasechangeloglock

jwt:
  secret: 0dlqiztCTu9qT5PCQsvOjTsiPyfhae5MsCeseF7I8kQ=
  access-token-expiration: 3000000 # 5 minutes = 300000
  refresh-token-expiration: 604800000 # 7 days
